# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

format A 24 2 0
leftstring A0 = "Hello"
leftstring B0 = "This is an example .csv file"
let A1 = 1
let B1 = 2
let C1 = 3
leftstring A2 = "\"This is quoted text\""
leftstring A3 = "'This is singley-quoted'"
goto A3 A0
